apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gluejobandrey.yaml
helmCharts:
  - name: xjobgluetemplate
    version: 0.1.0
    valuesFile: values.yaml
    releaseName: xjobgluetemplaterelease
    repo: https://sudopablosilva.github.io/helmcharts
