apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: platform-argocd-infra
    version: 0.1.0
    valuesFile: values.yaml
    releaseName: platform-argocd-infra
    repo: https://sudopablosilva.github.io/helmcharts/xjobgluetemplate-0.1.0.tgz
