apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controlplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sudopablosilva/mynewrepository'
    targetRevision: HEAD
    path: apps/controlplane
  destination:
    server: 'https://controlplane-cluster-url'
    namespace: controlplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
