apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- pairs:
    workloadtype: onebox
    shard: "2"

namePrefix: shard-2-onebox-

configMapGenerator:
- name: env-configmap
  literals: 
  - WORKLOAD_TYPE=onebox
  - SHARD=2

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeAffinity
      value:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: shard
                  operator: In
                  values:
                    - "2"
    - op: add
      path: /spec/template/spec/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0
      value:
        key: workloadtype
        operator: In
        values:
          - "onebox"
  target:
    kind: Deployment