apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: cluster
          operator: In
          values:
          - "cell-1"
      values:
        cluster: '{{.name}}'
        cellName: example_cell-1
        serviceName: example_opf
        clusterName: example_cell-1
        workloadType: example_onebox
        timeBetweenCanarySteps: example_5s
        imageTag: example_0.1
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: default
      source:
        helm:
          values: |
            podLabels:
              clusterlabel: '{{.cluster}}-{{.serviceName }}'
            cluster: {{.cluster }}
            cellName: {{.cellName }}
            serviceName: {{.serviceName }}
            clusterName: {{.clusterName }}
            workloadType: {{.workloadType }}
            timeBetweenCanarySteps: {{.timeBetweenCanarySteps }}
            image:
              tag: "{{.imageTag }}"
        path: example_opf
        repoURL: >-
          https://github.com/sudopablosilva/argo.git
        targetRevision: main
      destination:
        name: '{{.cluster}}'
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
