apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: example_cell-1
        cellName: example_cell-1
        serviceName: example_opf
        clusterName: example_cell-1
        workloadType: example_onebox
        timeBetweenCanarySteps: example_5s
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: default
      source:
        helm:
          values: |
            podLabels:
              clusterlabel: '{{.cluster}}-{{.serviceName }}'
            cluster: {{.cluster }}
            cellName: {{.cellName }}
            serviceName: {{.serviceName }}
            clusterName: {{.clusterName }}
            workloadType: {{.workloadType }}
            timeBetweenCanarySteps: {{.timeBetweenCanarySteps }}
        path: example_opf
        repoURL: >-
          https://github.com/sudopablosilva/argo.git
        targetRevision: main
      destination:
        name: '{{.cluster}}'
        namespace: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
