apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extratosvcsviahelm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sudopablosilva/mynewrepository'
    targetRevision: HEAD
    path: multipleshards/argocd/app_of_apps_via_helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
