name: rollback
description: 'O rollback será baseado na última execução com sucesso.'
title: "Solicitação de rollback"
labels: [rollback]

body:
  - type: dropdown
    attributes:
      label: ">>environment<<"
      description: "Insira o ambiente para o Rollback (dev/hom/prod)"
      options:
        - dev
        - hom
        - prod
    validations:
      required: true

  - type: input
    attributes:
      label: ">>cluster_name<<"
      description: "Insira o nome do cluster ECS aqui."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: ">>deployment_controller<<"
      description: "Escolha o tipo de deployment worker (tradicional ou onebox gradual)"
      options:
        - ECS/CodeDeploy
        - External
    validations:
      required: true

  - type: input
    attributes:
      label: ">>service_name_onebox<<"
      description: "Insira o nome do serviço ECS que tem o sufixo onebox SOMENTE se o deployment_controller selecionado for 'External'"
    validations:
      required: false

  - type: input
    attributes:
      label: "service_name"
      description: "Insira o nome do serviço ECS"
    validations:
      required: true
