name: "rollback"
description: 'The rollback will be based on the last successful execution.'
title: "Request for rollback"
labels: [rollback]

'on':
  issues:
    types: 
      - opened
      - labeled
      - unlabeled

  'workflow_dispatch':
    inputs:
      'environment':
        description: 'Environment for the rollback (dev/hom/prod)'
        required: true
        default: 'dev'
      'clusterName':
        description: 'Name of the ECS cluster'
        required: true
      'deploymentType':
        description: 'Type of Deployment (Traditional or Onebox Gradual)'
        required: true
        default: 'Traditional'
      'serviceNameOnebox':
        description: 'Name of the ECS service with the onebox suffix'
        required: true
      'serviceName':
        description: 'Name of the traditional ECS service'
        required: true
        
jobs:
  'rollback':
    'if': github.event.issue.labels.*.name == 'rollback'
    'runs-on': ubuntu-latest
    steps:
      - name: Check Issue Details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Rollback Type: Extract from issue body"

      - name: Convert Form Issue to JSON
        'runs-on': ubuntu-latest
        outputs:
          'payload-parsed': ${{ steps.payload.outputs.json_var }}
        steps:
          - name: Run Issue form parser
            id: parse
            uses: peter-murray/issue-forms-body-parser@v4.1.0
            with:
              issue_id: ${{ github.event.issue.number }}
              separator: '###'
              label_marker_start: '>>'
              label_marker_end: '<<'
  
          - name: Set output
            id: payload
            run: echo ::set-output name=json_var::'${{ steps.parse.outputs.payload }}'
  
          - name: Show output
            run: echo "${{ toJson(steps.payload.outputs.json_var) }}"
