spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sudopablosilva/mynewrepository
    targetRevision: HEAD
    path: multipleshards/apps/shard-1-normal
