apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- pairs:
    workloadtype: normal
    shard: "3"

namePrefix: shard-3-normal-

configMapGenerator:
- name: env-configmap
  literals: 
  - WORKLOAD_TYPE=normal
  - SHARD=3

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeAffinity
      value:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: shard
                  operator: In
                  values:
                    - "3"
    - op: add
      path: /spec/template/spec/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0
      value:
        key: workloadtype
        operator: In
        values:
          - "normal"
  target:
    kind: Deployment