name: EKS-Canary

on:
  push:
  workflow_dispatch:

env:
  MY_WORKFLOW_VARIABLE: "My workflow var value"
  SIGLA: ""

jobs:
  eks-onebox-gradual-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: azure/setup-kubectl@v3
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2

      - name: Update kube config
        run: aws eks update-kubeconfig --name management --region us-east-2

      - name: List pods
        run: kubectl get pods -A

      - name: Checkout code
        uses: actions/checkout@v4.1.3
        with:
          ref: develop

      - name: Set up Python
        uses: actions/setup-python@v5.1.0

      - name: Install Python dependencies
        run: python -m pip install pyyaml

      - name: Deploy to Clusters
        env:
          serviceName: openfinance
          templatePath: applicationsets.yaml
        run: python adapt_applicationsets.py

      - name: Deploy onebox workload
        run: kubectl apply -f modified_manifest_cell-1_onebox.yaml

      - name: Query cell-1-opf-high-severity-aggregate-rollback
        id: check_alarm
        run: |
          ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names "cell-1-opf-high-severity-aggregate-rollback" --alarm-types CompositeAlarm --region us-east-2 --query "CompositeAlarms[0].StateValue" --output text )
          echo "Alarm state: $ALARM_STATE"
          if [ "$ALARM_STATE" = "ALARM" ]; then
            echo "::set-output name=alarm_triggered::true"
          fi

      - name: Handle cell-1-opf-high-severity-aggregate-rollback
        if: steps.check_alarm.outputs.alarm_triggered == 'true'
        run: |
          echo "Alarm state is ALARM. Handling error..."
          exit 1

      - name: Query cell-1-opf-onebox-rollback-alarm
        id: check_alarm_onebox
        run: |
          ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names "cell-1-opf-onebox-rollback-alarm" --alarm-types CompositeAlarm --region us-east-2 --query "CompositeAlarms[0].StateValue" --output text )
          echo "Alarm state: $ALARM_STATE"
          if [ "$ALARM_STATE" = "ALARM" ]; then
            echo "::set-output name=alarm_triggered::true"
          fi

      - name: Handle cell-1-opf-onebox-rollback-alarm
        if: steps.check_alarm_onebox.outputs.alarm_triggered == 'true'
        run: |
          echo "Alarm state is ALARM. Handling error..."
          exit 1

      - name: Deploy normal
        run: kubectl apply -f modified_manifest_cell-1_normal.yaml
