name: EKS-Canary

on:
  push:
# https://docs.github.com/en/free-pro-team@latest/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
  workflow_dispatch:
    # inputs:
    #   subsys:
    #     type: string
    #     default: inputValue
    #   sigla:
    #     type: string
    #     default: SC4
    #   jobsuccess:
    #     type: string
    #     default: sucesso
    #   jobfailed:
    #     type: string
    #     default: falha
#   repository_dispatch:
#     types: [on-demand-test]

env:
  MY_WORKFLOW_VARIABLE: "My workflow var value"
  SIGLA: ""

jobs:
  deploy-eks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: azure/setup-kubectl@v3
        # with:
        #   version: '<version>' # default is latest stable
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
      - name: List pods
        run: |
          kubectl get pods
    # - uses: Azure/k8s-deploy@v4
      #   with:
      #     resource-group: yourResourceGroup
      #     name: yourClusterName
      #     action: deploy
      #     strategy: basic
      
      #     private-cluster: true
      #     manifests: |
      #       https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/controllers/nginx-deployment.yaml
      #     images: |
      #       nginx:1.14.3