name: JFrogIntegrationWorkflow2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
    
jobs:
  sourceStage:
    runs-on: ubuntu-latest
    steps:
      - name: Application Source
        run: echo "test"
      - name: Test Source
        run: echo "teste"
      - name: Infrastructure Source
        run: echo "teste"
      - name: Static Assets
        run: echo "teste"
      - name: Dependency Manifest
        run: echo "teste"
      - name: Configuration
        run: echo "teste"

  buildStage:
    runs-on: ubuntu-latest
    needs:
      - sourceStage
    steps:
      - name: Build Code
        run: echo "teste"
      - name: Unit Tests
        run: echo "teste"
      - name: Code Quality
        run: echo "teste"
      - name: Create annotation for build error
        run: echo "::notice file=app.js,line=1::Missing semicolon"
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
    
  TestBetaStage:
    needs:
      - buildStage
    runs-on: ubuntu-latest
    steps:
      - name: Launch Environment
        run: |
          echo "teste"
      - name: Deploy Software
        run: |
          echo "teste"
      - name: Integration Tests
        run: |
          echo "teste"

  TestGammaStage:
    needs:
      - TestBetaStage
    runs-on: ubuntu-latest
    steps:
      - name: Launch Environment
        run: |
          echo "teste"
      - name: Deploy Software
        run: |
          echo "teste"
      - name: Synthetic Tests
        run: |
          echo "teste"
      - name: DAST
        run: |
          echo "teste"
          
  ProdStage:
    needs:
      - TestGammaStage
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        run: |
          echo "teste"
      - name: Progressive Deployment
        run: |
          echo "teste"
      - name: Synthetic Tests
        run: |
          echo "teste"

  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
