name: JFrogIntegrationWorkflow2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
    
jobs:
  sourceStage:
    runs-on: ubuntu-latest
    steps:
      - name: Application Source
        run: echo "test"
      - name: Test Source
        run: echo "teste"
      - name: Infrastructure Source
        run: echo "teste"
      - name: Static Assets
        run: echo "teste"
      - name: Dependency Manifest
        run: echo "teste"
      - name: Configuration
        run: echo "teste"

  buildStage:
    runs-on: ubuntu-latest
    needs:
      - sourceStage
    steps:
      - name: Build Code
        run: echo "teste"
      - name: Unit Tests
        run: echo "teste"
      - name: Code Quality
        run: echo "teste"
      - name: Create annotation for build error
        run: echo "::notice file=app.js,line=1::Missing semicolon"

      
  TestBetaStage:
    needs:
      - buildStage
    runs-on: ubuntu-latest
    steps:
      - name: Launch Environment
        run: |
          echo "teste"
      - name: Deploy Software
        run: |
          echo "teste"
      - name: Integration Tests
        run: |
          echo "teste"

  TestGammaStage:
    needs:
      - TestBetaStage
    runs-on: ubuntu-latest
    steps:
      - name: Launch Environment
        run: |
          echo "teste"
      - name: Deploy Software
        run: |
          echo "teste"
      - name: Synthetic Tests
        run: |
          echo "teste"
      - name: DAST
        run: |
          echo "teste"
          
  ProdStage:
    needs:
      - TestGammaStage
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        run: |
          echo "teste"
      - name: Progressive Deployment
        run: |
          echo "teste"
      - name: Synthetic Tests
        run: |
          echo "teste"
