name: GitHubActionsDemo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
# https://docs.github.com/en/free-pro-team@latest/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
  workflow_dispatch:
    inputs:
      subsys:
        type: string
  repository_dispatch:
    types: [on-demand-test]
    
jobs:
#   print-tag:
#     runs-on: ubuntu-latest
#     if:  ${{ inputs.print_tags }} 
#     steps:
#       - name: Print subsys tag to STDOUT
#         run: echo The subsys value is ${{ inputs.subsys}}
#       - name: Print package tag to STDOUT
#         run: echo The package value is ${{ inputs.package}}
#       - name: Print funcao tag to STDOUT
#         run: echo The funcao value is ${{ inputs.funcao}}
#       - name: Print sitename tag to STDOUT
#         run: echo The sitename value is ${{ inputs.sitename}}
#       - name: Print jobsuccess tag to STDOUT
#         run: echo The jobsuccess value is ${{ inputs.jobsuccess}}
#       - name: Print jobfailed tag to STDOUT
#         run: echo The jobfailed value is ${{ inputs.jobfailed}}

  call-workflow-passing-data:
    uses: sudopablosilva/mynewrepository/.github/workflows/ReusableWorkflow.yml@main
    with:
      subsys: ${{ inputs.subsys }}

  anewjob:
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    steps:
      - name: Print Reusable output
        run: | 
          echo "The output is: ${{ needs.call-workflow-passing-data.outputs.myoutput }}"