name: GitHubActionsDemo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
# https://docs.github.com/en/free-pro-team@latest/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
  workflow_dispatch:
    inputs:
      subsys:
        type: string
        default: inputValue
  repository_dispatch:
    types: [on-demand-test]

# env:
#   MYVAR1: "arn:aws:iam::123456789012:user/Development/product_1234/*"

jobs:
  job1:
    outputs:
      MYOUTPUT: ${{ steps.step1.outputs.MYVAR2 }}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "MYVAR2=myvalue" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - run: echo "${{ needs.job1.outputs.MYOUTPUT }}"
#   print-tag:
#     runs-on: ubuntu-latest
#     if:  ${{ inputs.print_tags }} 
#     steps:
#       - name: Print subsys tag to STDOUT
#         run: echo The subsys value is ${{ inputs.subsys}}
#       - name: Print package tag to STDOUT
#         run: echo The package value is ${{ inputs.package}}
#       - name: Print funcao tag to STDOUT
#         run: echo The funcao value is ${{ inputs.funcao}}
#       - name: Print sitename tag to STDOUT
#         run: echo The sitename value is ${{ inputs.sitename}}
#       - name: Print jobsuccess tag to STDOUT
#         run: echo The jobsuccess value is ${{ inputs.jobsuccess}}
#       - name: Print jobfailed tag to STDOUT
#         run: echo The jobfailed value is ${{ inputs.jobfailed}}

  reusablejob:
    uses: sudopablosilva/mynewrepository/.github/workflows/ReusableWorkflow.yml@main
    with:
      subsys: ${{ inputs.subsys }}

  anotherjob:
    runs-on: ubuntu-latest
    needs: reusablejob
    steps:
      - name: Print Reusable output
        run: | 
          echo "The output is: ${{ needs.reusablejob.outputs.myworkflowoutput }}"
