on:
    push:
      branches:
        - develop
jobs:
    determine_environment:
      runs-on: ubuntu-latest
      outputs:
        env: ${{ steps.set-env.outputs.env }}
      steps:
        - uses: actions/checkout@v2
        - id: set-env
          run: |
            git log --oneline
            git rev-parse --is-shallow-repository
            git fetch --unshallow
            git log --oneline

            git show ${{ github.event.before }}
            git show ${{ github.event.after }}

            

            if git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | grep -q "^dev/"; then
              echo "env=dev" >> $GITHUB_OUTPUT
            elif git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | grep -q "^hom/"; then
              echo "env=hom" >> $GITHUB_OUTPUT
            elif git diff --name-only ${{ github.event.before }}..${{ github.event.after }} | grep -q "^prod/"; then
              echo "env=prod" >> $GITHUB_OUTPUT
            else
              echo "No environment-specific changes detected"
              exit 0
            fi
  
    config-parse:
      name: Parse IUPipes.yml
      runs-on: ubuntu-latest
      needs: determine_environment
      if: needs.determine_environment.outputs.env != ''
      steps:
      - run: |
            echo $environment
      env:
        environment: ${{ needs.determine_environment.outputs.env }}
  