name: Invoke ECS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2  # Centralized AWS region

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
